# User config
author: "Margaret Ruth"
tagline: "Yoga and Qi Gong"
description: "Margaret Ruth teaches yoga and qi gong in New York City."
keywords: "Margaret Ruth, Yoga, Qi Gong, qigong, New York, kid's yoga, children's yoga, brooklyn, yoga for kids, kid's yoga teachers, children's yoga teachers"
email: "mrgrtrth@gmail.com"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
